steps:
- name: 'gcr.io/cloud-builders/curl'
  id: 'get-worker-ip-formatted'
  entrypoint: 'sh'
  secretEnv: ['POSTGRES_PASS']
  args:
    - '-s'
    - '-c'
    - |
      printf "worker Pool IP : $(curl -s https://curlmyip.org)\n"
      
      # USE $$ TO ESCAPE. 
      # Cloud Build converts $$POSTGRES_PASS -> $POSTGRES_PASS
      # The shell then sees $POSTGRES_PASS and reads the secret.
      
      echo "Secret length is: $${#POSTGRES_PASS}" 

options:
  pool:
    name: 'projects/$PROJECT_ID/locations/$_LOCATION/workerPools/$_POOL_NAME'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _LOCATION: 'us-central1'
  _POOL_NAME: 'just-pool'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/postgres-password/versions/latest
    env: 'POSTGRES_PASS'
